### PR TITLE
Resolve only IPv4 addresses

### PR DESCRIPTION
**Pull request by dgadelha**
EOSERV does not totally support IPv6 (FIX for game.eoserv.net with IPv6-capable network)

### CODE REVIEW

**Comment by ethanmoffat** [comment]
This change breaks the alpha blending feature for map objects and actors by setting the Reach profile and removing use of the _playerBlend BlendState object in EOMapRenderer. See below screenshot:
image

The view should be like so, note the player glows a little (inventory inconsistency is a separate issue):
image

"HiDef" is required for the blend state that is in place. As far as I know there is no reason any graphics card from the last 10 years should be unable to handle the limited set of requirements to render this game.

The following changes are fine: 
- Proper release attributes (4eef7c5)
- Desc some exceptions, change client version font and position (2c98b34) - Segoe UI does not display correctly on my system (changing to "Segoe UI Regular" works fine). I have no alternate reports of Microsoft Sans Serif not working properly on other systems, there may be a graphics driver issue or OS incompatibility if you're on Vista or earlier. I develop on Win8 but have confirmed it works on Win7. I will add this note to the issue.
- Resolve IPv4 addresses (adfa886) (this one I might update to require a configuration value, if I add dual-mode sockets)

Please take some time to format the source code for consistency: set the editor to use tabs, 4 spaces per tab, and align them with the current code. Also please group any fields/properties with other relevant existing fields/properties for future changes.

**Comment by dgadelha** [comment]
Visual Studio 2015 :-1:

**Comment by dgadelha** [comment]
Also, I didn't knew GitHub put all the commits I done into Pull Request, I just did it for 1 commit, the IPv6 one.

**Comment by ethanmoffat** [comment]
Ahh ok. I'll look into merging just the one commit.

**Comment by dgadelha** [comment]
nah, i'm doing it.

**Pull request closed without merging**
